### ISSUE TITLE
question: etcd can't start when enable securityContext

### ISSUE THREAD

**Issue by TIEDPAG** [apache/apisix-helm-chart#105]
### 信息
version:  0.3.4

### 问题：
使用官网教程使用helm安装apisix时，出现etcd无法启动的问题，使用的命令如下：
```shell
helm install apisix apisix/apisix \
  --set admin.allow.ipList="{0.0.0.0/0}" \
  --namespace ingress-apisix
```
查看etcd日志错误如下：
> etcdmain: cannot access data directory: mkdir /bitnami/etcd/data: permission denied

**Comment by TIEDPAG** [comment]
前往查看bitnami/etcd 的helm chart，发现如下：
![image](https://user-images.githubusercontent.com/24646612/122706444-8a260780-d28a-11eb-8d2e-0a2bafc758fa.png)
检查values.yaml文件：
```yaml
## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  ## If true, use a Persistent Volume Claim, If false, use emptyDir
  ##
  enabled: true

## Init containers parameters:
## volumePermissions: Change the owner and group of the persistent volume mountpoint to runAsUser:fsGroup values from the securityContext section.
##
volumePermissions:
  enabled: false
  image:
    registry: docker.io
    repository: bitnami/minideb
    tag: buster
    pullPolicy: Always
```

尝试把volumePermissions设置为true，etcd正常启动，apisix也正常启动了

**Comment by TIEDPAG** [comment]
前往查看bitnami/etcd 的helm chart，发现如下：
![image](https://user-images.githubusercontent.com/24646612/122706444-8a260780-d28a-11eb-8d2e-0a2bafc758fa.png)
检查values.yaml文件：
```yaml
## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  ## If true, use a Persistent Volume Claim, If false, use emptyDir
  ##
  enabled: true

## Init containers parameters:
## volumePermissions: Change the owner and group of the persistent volume mountpoint to runAsUser:fsGroup values from the securityContext section.
##
volumePermissions:
  enabled: false
  image:
    registry: docker.io
    repository: bitnami/minideb
    tag: buster
    pullPolicy: Always
```

尝试把volumePermissions设置为true，etcd正常启动，apisix也正常启动了
