### ISSUE TITLE
k8s部署apisix后三方插件使用问题.

### ISSUE THREAD

**Issue by ccwxl** [apache/apisix-helm-chart#155]
使用官方的镜像部署到k8s后, 开发的三方插件的运行环境
1. 比如开发的一个go的插件. alpine 镜像中包含go运行的环境没. 这个场景有Example吗?
2. 自己开发的插件在k8s的环境下怎么放到pod上. 挂载吗? 有做过相关的例子

**Comment by spacewander** [comment]
Share the network namespace plus share the same /tmp mount point should be enough. As the apisix will communicate with Go runner via unix socket.

**Comment by Baoyuantop** [comment]
For third-party plugins (e.g., Go plugins) in a Kubernetes environment, the chart supports:

1. **Custom plugins via ConfigMap** (values.yaml lines 580-600):
```yaml
apisix:
  customPlugins:
    enabled: true
    luaPath: "/opts/custom_plugins/?.lua"
    plugins:
      - name: "your-plugin"
        configMap:
          name: "plugin-configmap"
          mounts:
            - key: "plugin.lua"
              path: "/opts/custom_plugins"
```

2. **External plugin runners** (Go/Python/Java) via sidecar containers:
```yaml
extraContainers:
  - name: go-runner
    image: your-go-plugin-image
extraVolumes:
  - name: plugin-socket
    emptyDir: {}
extraVolumeMounts:
  - name: plugin-socket
    mountPath: /tmp/runner.sock
```

See `extraContainers` (line 135), `extraVolumes` (line 114), and `extraVolumeMounts` (line 121) in values.yaml.

Closing as this is a usage question. If you still need help, please feel free to reopen.
