### ISSUE TITLE
Cannot set skywalking endpoint in helm installation? 

### ISSUE THREAD

**Issue by alanland** [apache/apisix-helm-chart#186]
I want use skywalking to monitor apisix request. [Documents](https://apisix.apache.org/docs/apisix/plugins/skywalking/)

## Software version
- Dashboard: 2.9.0
- Apisix:  2.10.0

## Reproduce steps

1. Enable `Skywalking` plugin  in dashboard 
2.  Edit `values.yaml`
    ```yaml
    customPlugins:
      enabled: true]
      plugins:
        - name: "skywalking"
          attrs: |
            service_name: APISIX
            service_instance_name: "APISIX Instance"
            endpoint_addr: http://myskywalking:12800
    ```
3. Run `helm upgrade ...`
4. Terminal outputs:
    ```sh
    Error: UPGRADE FAILED: template: apisix/templates/deployment.yaml:96:37: executing "apisix/templates/deployment.yaml" at <$plugin.configMap.mounts>: nil pointer evaluating interface {}.mounts
    ```
5. The values template is:
    ```yaml
    customPlugins:
      enabled: false
      # the lua_path that tells APISIX where it can find plugins,
      # note the last ';' is required.
      luaPath: "/opts/custom_plugins/?.lua"
      plugins:
          # plugin name.
        - name: ""
          # plugin attrs
          attrs: |
          # plugin codes can be saved inside configmap object.
          configMap:
            # name of configmap.
            name: ""
            # since keys in configmap is flat, mountPath allows to define the mount
            # path, so that plugin codes can be mounted hierarchically.
            mounts:
              - key: ""
                path: ""
              - key: ""
                path: ""
    ```
6. How to config `configMap` ?

Thanks!

**Comment by tokers** [comment]
"skywalking" is a built-in plugin, so you don't have to use `customPlugins`. Let's edit the plugin list to add the `skywalking`, see https://github.com/apache/apisix-helm-chart/blob/master/charts/apisix/values.yaml#L140 for details.

**Comment by alanland** [comment]
> "skywalking" is a built-in plugin, so you don't have to use `customPlugins`. Let's edit the plugin list to add the `skywalking`, see https://github.com/apache/apisix-helm-chart/blob/master/charts/apisix/values.yaml#L140 for details.

Thanks.

But my problem is cannot set skywalking in `values.yaml` endpoint, documents says to config plugin attr like:
```yaml
plugin_attr:
  skywalking:
    service_name: APISIX
    service_instance_name: "APISIX Instance Name"
    endpoint_addr: http://127.0.0.1:12800
```
when you configed `plugin_attr`，the `deployment.yaml` will create a`volumeMount`, that my real trouble.

Finally I solved it by rewrite `configmap.yaml` to apply plugin_attrs.

```yaml
    {{- if .Values.myCustomPlugins.enabled }}
    plugin_attr:
    {{- range $plugin := .Values.myCustomPlugins.plugins }}
      {{ $plugin.name }}: {{ $plugin.attrs | toYaml | nindent 8 }}
    {{- end }}
    {{- end }}
```
