### ISSUE TITLE
liunx aarch64 helm apisix chart can't  install

### ISSUE THREAD

**Issue by blank-1** [apache/apisix-helm-chart#202]
1. update  apisix/vaules.yaml
```
dashboard:
  enabled: true

ingress-controller:
  enabled: true
```

2.helm  install  apisix  apisix/  -n apisix

3.error msg
>

CrashLoopBackOff: back-off 5m0s restarting failed container=etcd pod=apisix-etcd-2_apisix(e60aa18d-8448-4fdc-94fe-b194abf82e85)
--

> standard_init_linux.go:228: exec user process caused: exec format error
![Uploading 2021-12-28_14-34-00.png…]()
