### ISSUE TITLE
missing TCP port after set stream tcp port on values file

### ISSUE THREAD

**Issue by labaq** [apache/apisix-helm-chart#224]
using stream on helm values, but gateway service not open stream port 9100
```
gateway:
  type: NodePort
  # If you want to keep the client source IP, you can set this to Local.
  # ref: https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip
  externalTrafficPolicy: Cluster
  # type: LoadBalancer
  # annotations:
  #   service.beta.kubernetes.io/aws-load-balancer-type: nlb
  externalIPs: []
  http:
    enabled: true
    servicePort: 80
    containerPort: 9080
  tls:
    enabled: false
    servicePort: 443
    containerPort: 9443
    existingCASecret: ""
    certCAFilename: ""
    http2:
      enabled: true
  stream:  # L4 proxy (TCP/UDP)
    enabled: true
    only: false
    tcp:
    - 9100
```
```
NAME                   TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
apisix-admin           ClusterIP   10.97.177.133   <none>        9180/TCP            33m
apisix-etcd            ClusterIP   10.104.172.79   <none>        2379/TCP,2380/TCP   33m
apisix-etcd-headless   ClusterIP   None            <none>        2379/TCP,2380/TCP   33m
apisix-gateway         NodePort    10.106.133.61   <none>        80:32011/TCP        33m
```
part of pod spec
```
spec:
  containers:
  - image: apache/apisix:2.10.0-alpine
    imagePullPolicy: IfNotPresent
    lifecycle:
      preStop:
        exec:
          command:
          - /bin/sh
          - -c
          - sleep 30
    name: apisix
    ports:
    - containerPort: 9080
      name: http
      protocol: TCP
    - containerPort: 9443
      name: tls
      protocol: TCP
    - containerPort: 9180
      name: admin
      protocol: TCP
    readinessProbe:
      failureThreshold: 6
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      tcpSocket:
        port: 9080
      timeoutSeconds: 1
    resources: {}
```

my question is that need open stream port on service and pod is that right?
or do i missing something to set

i want to proxy tcp service like redis or mysql
