### ISSUE TITLE
Request help: how to setup the gateway variables to enable HTTPS?

### ISSUE THREAD

**Issue by MirtoBusico** [apache/apisix-helm-chart#230]
Hi all,
I need to enable the https protocol on the apisisx ingress gateway.
I don't know how to setup the variables in the helm chart values.yaml to enable HTTPS.

My framework:

- 3 node kubernetes cluster
- Istio installed with the "minimal" profile
- apisix installed with helm chart (enabling ingress controller and dashboard)
- a working route and upstream for a site (eg "http://www.m01.net")

Now I want to setup apisix so that it responds to "https://www.m01.net"

What I have:

- a private Certificatiion Authority certificate
- key and certificate for www.m01.net signed by the private CA

The "**gateway**" part of values.yaml (modified as per [#851](https://github.com/apache/apisix-ingress-controller/issues/851) bug) is:
```
gateway:
  type: NodePort
  # If you want to keep the client source IP, you can set this to Local.
  # ref: https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip
  externalTrafficPolicy: Cluster
  # type: LoadBalancer
  # annotations:
  #   service.beta.kubernetes.io/aws-load-balancer-type: nlb
  externalIPs: []
  http:
    enabled: true
    servicePort: 80
    containerPort: 9080
  tls:
    enabled: false
    servicePort: 443
    containerPort: 9443
    existingCASecret: ""
    certCAFilename: ""
    http2:
      enabled: true
  stream:  # L4 proxy (TCP/UDP)
    enabled: true
    only: false
    tcp: # TCP proxy address list
      - 9100
      - "127.0.0.1:9101"
    udp: # UDP proxy address list
      - 9200
      - "127.0.0.1:9211"
  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: apisix.local
        paths: []
    tls: []
  #  - secretName: apisix-tls
  #    hosts:
  #      - chart-example.local

```
As far as I understand, I have to set "tls: enabled: true" but I don't know:

- what is tthe existingCASecret ?
- if the certCAFilename refers to the CA cert file, where have I to put that file so the helm cart find it?
- have I to enable "ingress"

There is any documentation / tutorial about this topic?

**Comment by gardun0** [comment]
Hey @MirtoBusico, in order to secure your gateway, there are many methods out there, this is one of them:

1. Enable TLS with `gateway.tls.enabled` set to `true`, this will add a `443` port for your service.
2. In order to expose your gateway, you must set the service to `LoadBalancer` type (alternative to Ingress).
3. As soon as your service set up, it'll have a public address with two ports `80` and `443`.
4. In order to have a TLS/SSL certificate there are many ways to do that but Let's Encrypt might do that Job for you, in this case we're using [cert-manager](https://cert-manager.io/).
5. You must set up an `Issuer`/`ClusterIssuer` with [cert-manager](https://cert-manager.io/) and a `Certificate`, that `Certificate` will generate a secret including the keys within your namespace (I don't remember if it must be the same as Apisix).
6. Once you have a `Certificate` resource created, you must create an `ApisixTls` resource referencing the same DNS you set on your `Certificate` and the secret name generated.
7. Finally you must change your domain DNS with the one generated trough your `LoadBalancer`.

Overall, this is a simple guide to secure your exposed gateway (I may missed something)

**Comment by MirtoBusico** [comment]
Thanks. I'll try asap

**Comment by MirtoBusico** [comment]
Hi @gardun0, I was able to do steps 1, 2, 3, and 7

I can't use Let's Encrypt (my lab have to work also in airgapped situation) and I should prefer not to add cert-manager to the things I have to learn.

For now I'm using CA and certificates created directly with openssl.
I have:

- m01ca.pem the Certification Authority certificate
- www.key the key for www.m01.net
- www.crt the certificate for www.m01.net
I know how to create a tls certificate in k8s
```
kubectl -n kube-system create secret tls www-ingress-tls --cert=www.crt --key=www.key
```
(note that I was only able to setup https in Istio Ingress gateway - mybe here secret type and namespace are different)

How can I create a certificate resource with these data?

**Comment by alucryd** [comment]
Are there any up to date instructions with the latest chart? I'm not sure how to make cert-manager and acme play nice with the gateway. As far as I can tell, the gateway itself is exposed as a LoadBalancer, not the ingress controller, so I'm a little lost compared to my usual workflow.

For say nginx or traefik, I'm used to creating a ClusterIssuer like so:
```
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer-apisix
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-key
    solvers:
    - http01:
        ingress:
          class: nginx
```

And then use annotations to automatically configure ingresses.

How does that translate to apisix? The documentation isn't very clear to me.

**Comment by alucryd** [comment]
Got it semi-working with acme, using a dns01 challenge doesn't require support on the apisix side so it's the way to go (fortunately our DNS provider has an API). Unfortunately though, SSL in Apisix is currently broken :/ https://github.com/apache/apisix/issues/9931

**Comment by neorjodyboy** [comment]
Hi. could anyone share a working values.yaml file for enabling ssl in apisix? tnx btw.

**Comment by Baoyuantop** [comment]
To enable HTTPS on the APISIX gateway, configure the SSL section in `values.yaml` (lines 308-326):

```yaml
apisix:
  ssl:
    enabled: true
    containerPort: 9443

service:
  tls:
    servicePort: 443
    nodePort: 32443  # if using NodePort
```

After enabling SSL, you need to configure SSL certificates through the APISIX Admin API or via CRDs. The chart handles the NGINX listener configuration; the actual TLS certificates are managed through APISIX's SSL resource objects.

Ref: https://apisix.apache.org/docs/apisix/certificate/

Closing as this is a usage question. If you still need help, please feel free to reopen.
