### ISSUE TITLE
Add option to enable control_api for apisix gateway

### ISSUE THREAD

**Issue by xgenvn** [apache/apisix-helm-chart#242]
In some scenarios where we need an endpoint to return 20x status for lb service health check (eg: on GKE, APISIX is configured to sit behind an ingress route).
The easiest way is to enable `control_api` when installing through helm and a way to configure health check configuration in deployment resource.

**Comment by tokers** [comment]
@xgenvn PR is welcome!

**Comment by tao12345666333** [comment]
Thanks for your report.

**Comment by xgenvn** [comment]
Hi all, I managed by a workaround using custom nginx.

In helm `values.yml`
```yaml
# Custom configuration snippet.
configurationSnippet:
  main: |

  httpStart: |

  httpEnd: |

  httpSrv: |
    location = /apisix/__healthcheck {                                                                                                                                                                                       
        allow all;                                                                                                                                                                                                 
        access_log on;
        return 200 'ok';                                                                                                                                                                                                   
    }
  httpAdmin: |

  stream: |
```

Then for GKE, use this example for BackendConfig
```
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: apisix-lb-backendconfig
spec:
  timeoutSec: 300
  healthCheck:
    checkIntervalSec: 60
    timeoutSec: 60
    healthyThreshold: 1
    unhealthyThreshold: 10
    requestPath: /apisix/__healthcheck
    type: HTTP
```

Ignore the content of this issue, exposing or enable `control_api` won't work.
