### ISSUE TITLE
`customPlugins.plugins[].name` is unuse

### ISSUE THREAD

**Issue by anjia0532** [apache/apisix-helm-chart#249]
values.yaml

https://github.com/apache/apisix-helm-chart/blob/cad35eceb4e21e6e23ca7cd221d72798f7ac3601/charts/apisix/values.yaml#L226-L228

template.yaml

https://github.com/apache/apisix-helm-chart/blob/cad35eceb4e21e6e23ca7cd221d72798f7ac3601/charts/apisix/templates/deployment.yaml#L122-L127

https://github.com/apache/apisix-helm-chart/blob/cad35eceb4e21e6e23ca7cd221d72798f7ac3601/charts/apisix/templates/deployment.yaml#L168-L174

Maybe change to 
```yaml

{{- range $plugin := .Values.customPlugins.plugins }}
  {{- range $mount := $plugin.configMap.mounts }}
    - mountPath: {{ $mount.path }}
      # name: plugin-{{ $plugin.configMap.name }} -> plugin-{{ $plugin.name }} ?
      name: plugin-{{ $plugin.name }}
      subPath: {{ $mount.key }}
  {{- end }}
  {{- end }}
```
