### ISSUE TITLE
help request:  Can't enable plugin authz-casdoor

### ISSUE THREAD

**Issue by airclear** [apache/apisix-helm-chart#313]
### Description

Environment and Config same as  apache/apisix#7279 

Install with Helm ,  Chart version : 0.10.0

helm config: 

```yaml
gateway:
  type: NodePort
  tls:
    enabled: true

dashboard:
  enabled: true
  image:
    repository: apache/apisix-dashboard
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: 2.13-alpine
  config:
    conf:
      etcd:
        # Supports defining multiple etcd host addresses for an etcd cluster
        endpoints:
          - etcd.ingress-apisix.svc.cluster.local:2379
        # apisix configurations prefix
        prefix: "/apisix"
        # Etcd basic auth info
        username: root
        password: root

etcd:
  # install etcd(v3) by default, set false if do not want to install etcd(v3) together
  enabled: false
  host:
    - http://etcd.ingress-apisix.svc.cluster.local:2379  # 直接使用自己安装的etcd

ingress-controller:
  enabled: true
  config.apisix.serviceNamespace: ingress-apisix

plugins:
  - api-breaker
  - authz-keycloak
  - basic-auth
  - batch-requests
  - consumer-restriction
  - cors
  - echo
  - fault-injection
  - grpc-transcode
  - hmac-auth
  - http-logger
  - ip-restriction
  - ua-restriction
  - jwt-auth
  - kafka-logger
  - key-auth
  - limit-conn
  - limit-count
  - limit-req
  - node-status
  - openid-connect
  - authz-casbin
  - authz-casdoor
  - prometheus
  - proxy-cache
  - proxy-mirror
  - proxy-rewrite
  - redirect
  - referer-restriction
  - request-id
  - request-validation
  - response-rewrite
  - serverless-post-function
  - serverless-pre-function
  - sls-logger
  - syslog
  - tcp-logger
  - udp-logger
  - uri-blocker
  - wolf-rbac
  - zipkin
  - traffic-split
  - gzip
  - real-ip
  - ext-plugin-pre-req
  - ext-plugin-post-req
stream_plugins:
  - mqtt-proxy
  - ip-restriction
  - limit-conn

```

config the route use curl : 

```
curl "http://apisix.xxxx.com:32380/apisix/admin/routes/3a8b12cf"  -H 'Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTc2ODQ4NjIsImlhdCI6MTY1NzY4MTI2Miwic3ViIjoiYWRtaW4ifQ.34vkMLKyjVjUQ5eC0Y9kCqEv98BvkmbXE6gw5-3Dkvk' -X PUT -d '
{
  "uri": "/anything/*",
  "name": "casdoor-httpbin",
  "methods": ["GET"],
  "host": "httpbin.xxxx.com",
  "plugins": {
    "authz-casdoor": {
        "endpoint_addr":"http://10.200.180.82:7001",
        "callback_url":"http://httpbin.xxxx.com:32380/anything/callback",
        "client_id":"223c6180503181a2da92",
        "client_secret":"b9add612d0142bfa3f9bd62cf0013e9cfbdd82ff"
    }
  },
  "upstream_id": "5ce57b8e",
  "status": 1
}'
```

It seems like the plugin `authz-casdoor` is not enabled

result like this:

```json
{"code":10000,"message":"schema validate failed: schema not found, path: plugins.authz-casdoor","data":null,"request_id":"b6be9eda-bd71-453f-a178-6462ed32b5f7"}
```

### Environment

- Install with Helm 
-  APISIX version (run apisix version): 2.14.1
- apache/apisix 2.14.1-alpine 382ae3df093d 3 weeks ago 148MB
- Operating system (run uname -a): Linux k0-node1 5.4.0-121-generic apache/apisix#137-Ubuntu SMP Wed Jun 15 13:33:07 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run openresty -V or nginx -V):
- etcd version, if relevant (run curl http://127.0.0.1:9090/v1/server_info):
- APISIX Dashboard version, if relevant: 2.13.0
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run luarocks --version): 3.8.0
