### ISSUE TITLE
How to provision plugin config and routes?

### ISSUE THREAD

**Issue by zar3bski** [apache/apisix-helm-chart#336]
Il am looking for way to preconfigure some plugins and routes based on `values.yaml`. Here is what I tried with the plugin **openid-connect** 
 
```yaml
pluginAttrs:  
  - name: openid-connect 
    client_id: xx
    client_secret: xx
    disable: false
    discovery: https://company.com/company.com/v2.0/.well-known/openid-configuration?p=B2C_1A_SIGNIN
    post_logout_redirect_uri: http://localhost:3000
    redirect_uri: http://localhost:3000/auth/callback
    scope: openid
```

Even though **openid-connect** appears in `plugins`, I can't find it activated in the dashboard when I deploy the stack. 

Do you have an example of what `pluginAttrs` is waiting for (if this is the way to configure plugins)?
