### ISSUE TITLE
how to set the values of consul

### ISSUE THREAD

**Issue by kellyseeme** [apache/apisix-helm-chart#352]
in the apisix helm chart,there is no way to set the values of consul,just to use values.yaml，if i want to use helm install --set ,how to do it ? thanks

**Comment by tokers** [comment]
I think this is a how-to problem about helm, see https://helm.sh/docs/intro/using_helm/#customizing-the-chart-before-installing.

**Comment by kellyseeme** [comment]
@tokers thanks,yes,its about helm,there is no way to set values use helm about --set:
--in the chart the _helpers.tpl:
    {{- if .Values.discovery.enabled }}
    discovery:
      {{- range $key, $value := .Values.discovery.registry }}
      {{ $key }}:
        {{- include "apisix.tplvalues.render" (dict "value" $value "context" $) | nindent 8 }}
      {{- end }}
    {{- end }}

--the template of the deployement :
{{/*
Renders a value that contains template.
Usage:
{{ include "apisix.tplvalues.render" ( dict "value" .Values.path.to.the.Value "context" $) }}
*/}}
{{- define "apisix.tplvalues.render" -}}
    {{- if typeIs "string" .value }}
        {{- tpl .value .context }}
    {{- else }}
        {{- tpl (.value | toYaml) .context }}
    {{- end }}
{{- end -}}

--the values.yaml:
values:
discovery:
  enabled: true
  registry:
    consul_kv:
      servers:
        - http://10.0.1.1:8500
        - http://10.0.1.1:8500
      prefix: "myservice"
   
  i found more articals,but can't find how to use --set

**Comment by Baoyuantop** [comment]
For custom Consul service discovery configuration, you can use `apisix.fullCustomConfig` in `values.yaml` (lines 335-340):

```yaml
apisix:
  fullCustomConfig:
    enabled: true
    config:
      apisix:
        # ... your full config here
      discovery:
        consul:
          servers:
            - "http://consul.example.com:8500"
          token: "your-token"
```

This gives you complete control over the APISIX `config.yaml`, including all discovery settings. Note that when `fullCustomConfig.enabled` is true, other `apisix.*` settings are ignored.

Closing as this is a usage question. If you still need help, please feel free to reopen.
