### ISSUE TITLE
Allows managing keys as secrets

### ISSUE THREAD

**Issue by nfrankel** [apache/apisix-helm-chart#358]
At the moment, the Apache APISIX Helm chart default [values](https://github.com/apache/apisix-helm-chart/blob/master/charts/apisix/values.yaml#L196-L198) looks like:

```yaml
admin:
  credentials:
    admin: edd1c9f034335f136f87ad84b625c8f1
    viewer: 4054f7cf07e344346cd3f287985e76a2
```

To override them, I need to set them "in clear".

It would be better to manage them as Kubernetes Secrets.
