### ISSUE TITLE
Found a bug in the helm template

### ISSUE THREAD

**Issue by TOT-JIN** [apache/apisix-helm-chart#379]
Platform: 1.24.3-aliyun.1
apisix: 2.15.0
helm.sh/chart: apisix-0.11.1

Upstream doesn't work when apisix is installed using helm
Error log:

```

http_access_phase(): failed to set upstream: no valid upstream node: nil

```

After investigation, there is a problem with ClusterRole, and apisix needs to maintain the get permission for endpoints:

```

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    meta.helm.sh/release-name: apisix
    meta.helm.sh/release-namespace: ingress-apisix
  labels:
    app.kubernetes.io/managed-by: Helm
  name: apisix
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get         # add this line
  - list
  - watch

```

I will submit a PR for [https://github.com/apache/apisix-helm-chart/blob/master/charts/apisix/templates/clusterrole.yaml] later.
