### ISSUE TITLE
empty name in customPlugins cause various errors

### ISSUE THREAD

**Issue by abalage** [apache/apisix-helm-chart#395]
Hello,

I am using 2.15.0 from helm chart 0.11.2.

I configure customPlugins according to the sample from [values.yaml](https://github.com/apache/apisix-helm-chart/blob/b2f13ac7d8309174fcbb528cba244724b9f1d22f/charts/apisix/values.yaml#L287).
The content of the custom plugin does not matter.

The `name` key is an empty string in the example above. However its value is used for concatenation when the [plugins: list is evaluated](https://github.com/apache/apisix-helm-chart/blob/b2f13ac7d8309174fcbb528cba244724b9f1d22f/charts/apisix/templates/configmap.yaml#L277). 

It creates a plugins list like this one below. Note the extra `-` character in plugins: definition.
```
etcd:
  host:                                 # it's possible to define multiple etcd hosts addresses of the same etcd cluster.
    - "http://apisix-etcd.foobar.svc.cluster.local:2379/"
  prefix: "/apisix"     # apisix configurations prefix
  timeout: 30   # 30 seconds
plugins:                          # plugin list
  - add-custom-headers
  - jwt-as-bearer
  - cors
  - authz-keycloak
  - proxy-rewrite
  - redirect
  - prometheus
  - serverless-post-function
  -
stream_plugins:
  - mqtt-proxy
```

It has several consequences like manifesting errors in apisix.
```
2022/11/15 14:02:33 [warn] 46#46: *2 [lua] json.lua:94: failed to encode: Cannot serialise table: table key must be a number or string force: nil, context: init_worker_by_lua*
2022/11/15 14:02:33 [warn] 46#46: *2 [lua] json.lua:94: failed to encode: Cannot serialise table: table key must be a number or string force: nil, context: init_worker_by_lua*
2022/11/15 14:02:33 [warn] 46#46: *2 [lua] plugin.lua:194: load(): new plugins: , context: init_worker_by_lua*
...
2022/11/15 14:02:33 [error] 46#46: init_worker_by_lua error: /usr/local/apisix/apisix/plugin.lua:109: attempt to concatenate local 'name' (a table value)
stack traceback:
	/usr/local/apisix/apisix/plugin.lua:109: in function 'load_plugin'
	/usr/local/apisix/apisix/plugin.lua:213: in function 'load'
	/usr/local/apisix/apisix/plugin.lua:332: in function 'load'
	/usr/local/apisix/apisix/plugin.lua:681: in function 'init_worker'
	/usr/local/apisix/apisix/init.lua:138: in function 'http_init_worker'
	init_worker_by_lua:2: in main chunk
```

And also causes ingress controller to fail:
```
3397 2022-11-15T20:13:29+08:00>--^[[31merror^[[0m>---apisix/pluginconfig.go:164>-failed to create pluginConfig: unexpected status code 400; error message: {"error_msg":"unknown plugin [cors]"}
3399 2022-11-15T20:13:29+08:00>--^[[33mwarn^[[0m>ingress/apisix_pluginconfig.go:261>-sync ApisixPluginConfig failed, will retry>-{"object": {"Type":1,"Object":{"Key":"foo/example-apc","OldObject":null,"GroupV     ersion":"apisix.apache.org/v2"},"OldObject":null,"Tombstone":null}, "error": "1 error occurred:\n\t* unexpected status code 400; error message: {\"error_msg\":\"unknown plugin [cors]\"}\n\n\n"}
3400 2022-11-15T20:13:29+08:00>--^[[31merror^[[0m>---ingress/status.go:336>--unsupported resource record: &{{ } {example-apc  bar  4c33e65b-f7a9-4673-9c26-782f7d54fde6 67056101 %!s(int64=1) 2022-11-15 20:05:2     4 +0800 HKT <nil> %!s(*int64=<nil>) map[] map[] [] [] [{OpenAPI-Generator Update apisix.apache.org/v2 2022-11-15 20:05:24 +0800 HKT FieldsV1 {"f:spec":{".":{},"f:plugins":{}}} }]} {[{-- removed content --} {cors %!s(bool=true) map[allow_origins:http://localhost:4200]}]} {[]}}
```

Manually removing the extra dash character from configMap representing config.yml makes it work.
I tried to give a name to the customPlugin instead of leaving empty but it caused another error.

```
2022/11/16 14:14:11 [error] 44#44: *3 [lua] plugin.lua:118: load_plugin(): failed to load plugin [foobar] err: module 'apisix.plugins.foobar' not found:
	no field package.preload['apisix.plugins.foobar']
	no file '/usr/local/custom/apisix/plugins/foobar.lua'
	no file '/usr/local/apisix//deps/share/lua/5.1/apisix/plugins/foobar.lua'
	no file '/usr/local/apisix//deps/share/lua/5.1/apisix/plugins/foobar/init.lua'
	no file '/usr/local/apisix/apisix/plugins/foobar.lua'
	no file '/usr/local/apisix/apisix/plugins/foobar/init.lua'
	no file '/usr/local/openresty/site/lualib/apisix/plugins/foobar.ljbc'
	no file '/usr/local/openresty/site/lualib/apisix/plugins/foobar/init.ljbc'
	no file '/usr/local/openresty/lualib/apisix/plugins/foobar.ljbc'
	no file '/usr/local/openresty/lualib/apisix/plugins/foobar/init.ljbc'
	no file '/usr/local/openresty/site/lualib/apisix/plugins/foobar.lua'
	no file '/usr/local/openresty/site/lualib/apisix/plugins/foobar/init.lua'
	no file '/usr/local/openresty/lualib/apisix/plugins/foobar.lua'
	no file '/usr/local/openresty/lualib/apisix/plugins/foobar/init.lua'
	no file './apisix/plugins/foobar.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/apisix/plugins/foobar.lua'
	no file '/usr/local/share/lua/5.1/apisix/plugins/foobar.lua'
	no file '/usr/local/share/lua/5.1/apisix/plugins/foobar/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/apisix/plugins/foobar.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/apisix/plugins/foobar/init.lua'
	no file './apisix/plugins/foobar.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/apisix/plugins/foobar.lua'
	no file '/usr/local/share/lua/5.1/apisix/plugins/foobar.lua'
	no file '/usr/local/share/lua/5.1/apisix/plugins/foobar/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/apisix/plugins/foobar.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/apisix/plugins/foobar/init.lua'
	no file '/usr/local/openresty/site/lualib/apisix/plugins/foobar.ljbc'
	no file '/usr/local/openresty/site/lualib/apisix/plugins/foobar/init.ljbc'
	no file '/usr/local/openresty/lualib/apisix/plugins/foobar.ljbc'
	no file '/usr/local/openresty/lualib/apisix/plugins/foobar/init.ljbc'
	no file '/usr/local/openresty/site/lualib/apisix/plugins/foobar.lua'
	no file '/usr/local/openresty/site/lualib/apisix/plugins/foobar/init.lua'
	no file '/usr/local/openresty/lualib/apisix/plugins/foobar.lua'
	no file '/usr/local/openresty/lualib/apisix/plugins/foobar/init.lua'
	no file './apisix/plugins/foobar.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/apisix/plugins/foobar.lua'
	no file '/usr/local/share/lua/5.1/apisix/plugins/foobar.lua'
	no file '/usr/local/share/lua/5.1/apisix/plugins/foobar/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/apisix/plugins/foobar.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/apisix/plugins/foobar/init.lua'
	no file '/usr/local/apisix//deps/lib64/lua/5.1/apisix/plugins/foobar.so'
	no file '/usr/local/apisix//deps/lib/lua/5.1/apisix/plugins/foobar.so'
	no file '/usr/local/openresty/site/lualib/apisix/plugins/foobar.so'
	no file '/usr/local/openresty/lualib/apisix/plugins/foobar.so'
	no file './apisix/plugins/foobar.so'
	no file '/usr/local/lib/lua/5.1/apisix/plugins/foobar.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/apisix/plugins/foobar.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './apisix/plugins/foobar.so'
	no file '/usr/local/lib/lua/5.1/apisix/plugins/foobar.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/apisix/plugins/foobar.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/usr/local/apisix//deps/lib64/lua/5.1/apisix.so'
	no file '/usr/local/apisix//deps/lib/lua/5.1/apisix.so'
	no file '/usr/local/openresty/site/lualib/apisix.so'
	no file '/usr/local/openresty/lualib/apisix.so'
	no file './apisix.so'
	no file '/usr/local/lib/lua/5.1/apisix.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/apisix.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './apis
```

The only viable workaround at the moment is manually editing the provisioned configmap.

Should you have any questions please let me know.

**Comment by tokers** [comment]
Is this an accidental event? Or it's intentional?

**Comment by abalage** [comment]
Sorry, what do you mean?
My intention was to use customPlugins. The sample does not specify a name just an zero length string which is later used for concatenation. If I provide an arbitrary name for the plugin, no plugin with that name will be found.
I am not clearly aware of  the root cause but removing that extra dash character from the generated configmap seemed to resolve it.

This is the helm config I use. Maybe it helps you to reproduce the issue.

```
dashboard:
  enabled: true
  image:
    tag: 2.13-alpine
  config:
    authentication:
      secret: secret
      expireTime: 3600
      users:
        - username: admin
          password: secretadminpasswordfordashboard

admin:
  enabled: true
  credentials:
    admin: secretadminpassword
    viewer: secretviewerpassword

etcd:
  enabled: true
  replicaCount: 1
  timeout: 30

gateway:
  type: LoadBalancer
  stream:
    enabled: true
    only: false

apisix:
  image:
    tag: 2.15.0-alpine
  timezone: Europe/Budapest
  enableIPv6: false
  extraEnvVars:
    - name: PLUGIN_ATTR_PROMETHEUS_EXPORT_ADDR_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP

customPlugins:
  enabled: true
  luaPath: "/usr/local/custom/?.lua"
  plugins:
    - name: ""
      configMap:
        name: foobar-plugins-config
        mounts:
          - key: plugin1.lua
            path: /usr/local/custom/apisix/plugins/plugin1.lua
          - key: plugin2.lua
            path: /usr/local/custom/apisix/plugins/plugin2.lua

pluginAttrs:
  redirect:
    https_port: 443
  prometheus:
    prefer_name: true
    export_addr:
      ip: ${{PLUGIN_ATTR_PROMETHEUS_EXPORT_ADDR_IP}}
plugins:                           # plugin list (sorted by priority)
  - plugin1             # priority: 24000
  - plugin2                  # priority: 23999
  - cors                           # priority: 4000
  - authz-keycloak                 # priority: 2000
  - proxy-rewrite                  # priority: 1008
  - redirect                       # priority: 900
  - prometheus                     # priority: 500
  # <- recommend to use priority (0, 100) for your custom plugins
  - serverless-post-function       # priority: -2000
  
configurationSnippet:
  stream: |
    #server {
    #  removed-content;
    #}

ingress-controller:
  enabled: true
  image:
    tag: 1.5.0
  config:
    enableProfiling: false
    kubernetes:
      appNamespaces: ["foobar"]
    apisix:
      serviceNamespace: foobar
      adminKey: secretadminpassword
```
I applied it  manually.
`$ helm --version=0.11.2 upgrade -i --reset-values --force --values=helm-config.yaml apisix apisix/apisix -n foobar`
