### ISSUE TITLE
helm apisix no support  multiple ports and custom http2 port

### ISSUE THREAD

**Issue by sweetpotatoman** [apache/apisix-helm-chart#404]
I want to configure [grpc proxy](https://apisix.apache.org/docs/apisix/2.15/grpc-proxy/) 
but apisix helm templates don't seem to support.

configmap
```yaml
...
    apisix:
      node_listen: {{ .Values.gateway.http.containerPort }}    # APISIX listening port
...
```
