### ISSUE TITLE
CRD definition of ApisixRoute/v2alpha1 is missing from charts/apisix-ingress-control/crds

### ISSUE THREAD

**Issue by tokers** [apache/apisix-helm-chart#43]
The newest version of `ApisixRoute` is `v2alpha1`.

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: apisixroutes.apisix.apache.org
spec:
  group: apisix.apache.org
  versions:
    - name: v1
      served: true
      storage: false
    - name: v2alpha1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: apisixroutes
    singular: apisixroute
    kind: ApisixRoute
    shortNames:
      - ar
```

While the CRD definition in charts/apisix-ingress-controller/crds doesn't contain the `v2alpha1`, we should add it.
