### ISSUE TITLE
bug: apisix access log is corrupted when accessLogFormatEscape is set to json

### ISSUE THREAD

**Issue by ikatlinsky** [apache/apisix-helm-chart#452]
After logs configuration is updated to support json format

```yaml
logs:
  enableAccessLog: true
  accessLog: "/dev/stdout"
  accessLogFormat: '{"@timestamp": "$time_iso8601"}'
  accessLogFormatEscape: json
  errorLog: "/dev/stderr"
  errorLogLevel: "warn"
```

or 

```yaml
logs:
  enableAccessLog: true
  accessLog: "/dev/stdout"
  accessLogFormat: "{\"@timestamp\": \"$time_iso8601\"}"
  accessLogFormatEscape: json
  errorLog: "/dev/stderr"
  errorLogLevel: "warn"
```

logs became corrupted as only `{` is displayed instead of the complete log.

Actual result

```
2023/01/14 22:11:00 [warn] 50#50: *3099 [lua] plugin.lua:929: encrypt_conf(): failed to get schema for plugin: proxy-rewrite, client: 10.193.17.38, server: , request: "PUT /apisix/admin/routes/e223d1cf HTTP/1.1", host: "apisix-admin.acl.svc.cluster.local:9180"
{
{
{
{
```

Expected result

```
2023/01/14 22:14:00 [warn] 50#50: *3151 [lua] plugin.lua:929: encrypt_conf(): failed to get schema for plugin: serverless-post-function, client: 10.193.17.38, server: , request: "PUT /apisix/admin/routes/b1abdee6 HTTP/1.1", host: "apisix-admin.acl.svc.cluster.local:9180"
{"@timestamp": "2023-01-14T22:13:59+03:00"}
{"@timestamp": "2023-01-14T22:13:59+03:00"}
{"@timestamp": "2023-01-14T22:13:59+03:00"}
{"@timestamp": "2023-01-14T22:13:59+03:00"}
```
