### ISSUE TITLE
feat: Support configuring APISIX admin_key via secret

### ISSUE THREAD

**Issue by tao12345666333** [apache/apisix-helm-chart#476]
APISIX has supported the ability to configure via environment variables.

https://github.com/apache/apisix/blob/master/conf/config.yaml#L28

For more security and convenience, users would like to store admin_key through secret or other components.

We can also add this capability.

Add a new configuration item in `values.yam`l and use the existing secret to store `admin_key `. At creation time, let APISIX use this value by mounting the secret as an environment variable.

**Comment by marcuskrantz** [comment]
This is exactly the use case that I have. It would be ideal to:

1) First create the secret. This can either be done manually or through some third-party product like external-secrets.io.

`kubectl -n kong create secret generic apisix-credentials --from-literal=adminKey="my_secret_admin_key"`

2) Configure APISIX Ingress to pick up credentials from the secret. In deployment.yaml:

```
spec:
  ...
  env:
  - name: DEFAULT_CLUSTER_ADMIN_KEY
      valueFrom:
        secretKeyRef:
          key: "adminKey"
          name: "apisix-credentials"
```
