### ISSUE TITLE
Apisix Helm Questions

### ISSUE THREAD

**Issue by coffeebe4code** [apache/apisix-helm-chart#486]
First of all, great product very easy to get set up!

I'm wondering what the recommendation or purpose behind the `values` for `apisix.kind` being either `Deployment` or `DaemonSet`. My understanding is that Deployment still should be getting the data from data, and control plane.

I'm also not entirely sure which mode we are running in. I believe it is traditional, but it could be decoupled. What values am I looking for to be able to tell?
Here are the main values.
```
apisix.enabled: true
apisix.kind: Deployment
gateway.type: NodePort
admin.enabled: true
admin.type: ClusterIP
autoscaling.enabled: true
```

**Comment by Gallardot** [comment]
Please refer to this issue #225 . Deploying apisix in `Deployment` or `DaemonSet` depends entirely on your application scenario, which is currently default to `Deployment`.

ps:
[Deployment](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/) and [DaemonSet](https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/) are workload types in Kubernetes, and [Deployment modes in apisix](https://apisix.apache.org/docs/apisix/deployment-modes/) are not the same thing.

**Comment by coffeebe4code** [comment]
@Gallardot thank you for the quick response.

I looked at that file, and sure enough there was information related to the deployment type in the `deployment:` section.

I scanned through the values file provided in the helm version I pulled, the Chart.yaml has these values.
```
annotations:
  artifacthub.io/prerelease: "false"
apiVersion: v2
appVersion: 3.1.0
dependencies:
- condition: etcd.enabled
  name: etcd
  repository: https://charts.bitnami.com/bitnami
  version: 8.3.4
- alias: ingress-controller
  condition: ingress-controller.enabled
  name: apisix-ingress-controller
  repository: https://charts.apiseven.com
  version: 0.11.3
description: A Helm chart for Apache APISIX v3
icon: https://apache.org/logos/res/apisix/apisix.png
maintainers:
- name: tao12345666333
name: apisix
sources:
- https://github.com/apache/apisix-helm-chart
type: application
version: 1.1.0
```
I searched the project and couldn't find anything related to `deployment`, `decoupled` or `traditional`. I'm wondering if this is an older, newer, or enterprise version of the chart. No worries either way.

I looked over the PR and for DaemonSet vs Deployment. I think I am happy with Deployment, and also happy with `traditional` mode.

Thank you! 💯
