### ISSUE TITLE
Can't visit other pod in one Node

### ISSUE THREAD

**Issue by riskgod** [apache/apisix-helm-chart#50]
Hey, I deploy a new grpc service in local k8s and this service can visit in my local, but when I use apisix's upstearm to visit it, this not works. 
![image](https://user-images.githubusercontent.com/3436287/112989349-65445b80-9197-11eb-90b3-ba85f7a8e764.png)
![image](https://user-images.githubusercontent.com/3436287/112989357-683f4c00-9197-11eb-9e05-ed4a4a493863.png)
![image](https://user-images.githubusercontent.com/3436287/112989363-6bd2d300-9197-11eb-8b82-4f855ab0d3ef.png)

# This is my depolyment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-node
  labels:
    app: grpc-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-node
  template:
    metadata:
      labels:
        app: grpc-node
    spec:
      containers:
      - name: grpc-node
        imagePullPolicy: IfNotPresent
        image: grpc-test-node
        ports:
        - containerPort: 50051
  ```
## After apply the deployment successful, I run under commands
```
$ kubectl expose deployment/grpc-node
$ kubectl patch svc grpc-node -p '{"spec": {"type": “NodePort”}}’
```
