### ISSUE TITLE
dashboard has no consul option, only consul kv, why?

### ISSUE THREAD

**Issue by kkTea** [apache/apisix-helm-chart#509]
**description:**
After configuring consul in values.yaml, the service discovery type has no consul option, only consul kv, how should I configure it correctly?

**my config**
```yaml
discovery:
  consul:
    servers:
      - "http://127.0.0.1:8500"
```

![image](https://user-images.githubusercontent.com/54537817/224623551-260c4747-4cbf-4ae1-9864-a18e82d78559.png)
