### ISSUE TITLE
etcd chart support defrag cronjob config

### ISSUE THREAD

**Issue by Fabriceli** [apache/apisix-helm-chart#513]
Make a more reliable etcd cluster, can we add this config in etcd chart:
```yaml
defrag:
  ## @param defrag.enabled Enable auto defrag by periodically
  ##
  enabled: true
  cronjob:
    # -- Specifies how to treat concurrent executions of a Job. Valid values are: `Allow`, `Forbid` and `Replace`.
    concurrencyPolicy: "Forbid"
    # -- The number of failed finished jobs to retain.
    failedJobsHistoryLimit: "1"
    # -- The schedule in Cron format, see https://en.wikipedia.org/wiki/Cron.
    schedule: "0 0 * * *"
    # -- Optional deadline in seconds for starting the job if it misses scheduled time for any reason. Missed jobs executions will be counted as failed ones.
    startingDeadlineSeconds: "30"
    # -- The number of successful finished jobs to retain.
    successfulJobsHistoryLimit: "3"
    # -- This flag tells the controller to suspend subsequent executions, it does not apply to already started executions.
    suspend: false
  config:
    # -- gRPC endpoints
    endpoints:
      - apisix-etcd-0.apisix-etcd-headless.apisix-etcd.svc.cluster.local:2379
      - apisix-etcd-1.apisix-etcd-headless.apisix-etcd.svc.cluster.local:2379
      - apisix-etcd-2.apisix-etcd-headless.apisix-etcd.svc.cluster.local:2379
```
