### ISSUE TITLE
apisix pod报错

### ISSUE THREAD

**Issue by chenjinkai** [apache/apisix-helm-chart#529]
问题描述：
1. 采用了外部etcd，并且配置https访问etcd
2. 报错内容如截图
![1680592864902](https://user-images.githubusercontent.com/2556749/229717831-bfcf0784-424c-414c-8e14-bda16d4aacbb.png)
3. 内网环境采用helm离线包部署，配置如下
![1680593517887](https://user-images.githubusercontent.com/2556749/229720247-1e382c2f-628c-4a3f-9e84-3d89114c67b2.png)

4.  在secret配置了etcd-ssl secret，内容包含了etcd的证书 
![1680593567969](https://user-images.githubusercontent.com/2556749/229720452-5ab061e9-659b-4007-806a-b9b9593330f0.png)

**Comment by flylan** [comment]
Although I don't quite know how to solve your problem, I feel that asking questions in English may make your answers easier to answer

**Comment by flylan** [comment]
Although Apisix was born in China, it has now contributed to the Apache Foundation, and more and more people from other countries will participate. If you keep answering your questions in Chinese, even if others have answered your questions and helped you solve them, your questions will be of little help to others who cannot understand Chinese, and this will also reduce the enthusiasm of others to answer your questions

**Comment by Baoyuantop** [comment]
The current chart fully supports connecting to external etcd via HTTPS/TLS. Configure the following in `values.yaml`:

```yaml
etcd:
  enabled: false  # disable built-in etcd
  host:
    - "https://your-etcd-host:2379"
  auth:
    tls:
      enabled: true
      existingSecret: "your-etcd-tls-secret"  # Secret with certs
      certFilename: "cert.pem"
      certKeyFilename: "key.pem"
      verify: true
      sni: ""
```

See values.yaml lines 648-666 for all etcd TLS options. The Secret should contain the client certificate, client key, and optionally the CA certificate.

Closing as this is a usage question. The chart supports this functionality. If you still have questions, please feel free to reopen.
