### ISSUE TITLE
Priority optional field is missing from CRD after is applied to k8s

### ISSUE THREAD

**Issue by alita1991** [apache/apisix-helm-chart#531]
During the process of applying the Apisix CRDs via kubectl, I discovered that the priority field was missing on the live manifest. This issue was brought to my attention by the ArgoCD sync process, which detected the absence of the priority field in the applied CRD.

The following CRDs are impacted by this issue:

- [apisixroutes.apisix.apache.org](http://apisixroutes.apisix.apache.org/)
- [apisixpluginconfigs.apisix.apache.org](http://apisixpluginconfigs.apisix.apache.org/)

I'm looking for a way to ensure that the desired manifest is equal to the applied manifest, otherwise, ArgoCD SYNC will fail.

**Comment by lsoica** [comment]
Hit this as well. The problem is that for the default priority value of "0", it is stripped by the api server on get operations. Was the priority field with default value added for a specific reason?

**Comment by xpicio** [comment]
Hello, i have the same issue. At the moment i fixed with this configuration on Argo CD application:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apisix
  namespace: argo-cd
spec:
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jqPathExpressions:
        - '.spec.versions[].additionalPrinterColumns[]'
```

Now the sync process it's works 👋
