### ISSUE TITLE
Allow to provide etcd credentials from secret for gateway

### ISSUE THREAD

**Issue by ikatlinsky** [apache/apisix-helm-chart#554]
**Motivation**

Currently, there is no way to provide external etcd user and password values from secret. One should provide plain data in a values file, which is not a secured way.

**Proposal**

Allow providing etcd credentials from existing secret using the following settings

```
etcd:
  user: ""
  password: ""
  # -- Name of the existing secret containing user and password for external etcd, overrides etcd.user and etcd.password
  existingSecret: ""
  # -- Name of key containing username to be retrieved from the existing secret, has a value of user by default
  existingSecretUserKey: ""
  # -- Name of key containing password to be retrieved from the existing secret, has a value of password by default
  existingSecretPasswordKey: ""
```

The same should be applied to rbac auth for etcd.
