### ISSUE TITLE
Support for adding metrics relabeling config in Servicemonitor template

### ISSUE THREAD

**Issue by hemalatha2808** [apache/apisix-helm-chart#574]
Hi Team,

We have a requirement of adding metric relabeling config to servicemonitor of apisix helm chart in order to make some alterations to the existing metric labels.

Currently, we don't have this provision available in servicemoitor template file. If possible, can you please update the servicemonitor to accomplish this change?

**Similar to this:**

```
serviceMonitor:
   enabled: true
   endpoints:
       metricRelabelConfig:
       - sourceLabels: [request_uri]
          regex: *.png
          action: drop
```

**Reference doc**: https://medium.com/quiq-blog/prometheus-relabeling-tricks-6ae62c56cbda
