### ISSUE TITLE
version 3.3.0 apisix gateway can't listen on 443

### ISSUE THREAD

**Issue by gy8409** [apache/apisix-helm-chart#575]
Here is the logs in apisix deployment pod:

`/usr/local/openresty//luajit/bin/luajit ./apisix/cli/apisix.lua init_etcd
--
Thu, Jul 6 2023 4:41:43 pm | 2023/07/06 16:41:43 [emerg] 1#1: bind() to 0.0.0.0:443 failed (13: Permission denied)
Thu, Jul 6 2023 4:41:43 pm | nginx: [emerg] bind() to 0.0.0.0:443 failed (13: Permission denied)
`

chart version: 2.0.0
apisix version: 3.3.0-debian

**Comment by holubovskyi** [comment]
Hi @gy8409, I use the following values to work around it
```
podSecurityContext:
  sysctls:
  - name: net.ipv4.ip_unprivileged_port_start
    value: "1"
```

**Comment by Baoyuantop** [comment]
The `bind() to 0.0.0.0:443 failed (13: Permission denied)` error occurs because port 443 is a privileged port (< 1024) that requires root or the `NET_BIND_SERVICE` capability. The chart runs APISIX as non-root by default.

**Solutions:**
1. **Use a high port** (recommended): Set `apisix.ssl.containerPort: 9443` (values.yaml line 310, this is the default)
2. **Add capability**: Configure `securityContext` (values.yaml lines 47-53):
```yaml
securityContext:
  capabilities:
    add:
      - NET_BIND_SERVICE
```

The default SSL container port is already 9443, so this issue typically arises from custom overrides.

Closing as this is a usage question about Linux port binding. If you still have questions, please feel free to reopen.
