### ISSUE TITLE
feat: allow to use templates as values for apisix pod annotations

### ISSUE THREAD

**Issue by ikatlinsky** [apache/apisix-helm-chart#586]
**Problem**

Currently, apisix allows to use only plain text values for apisix pod annotation. There can be cases when some template value should be rendered, for example:

```yaml
podAnnotations:
  checksum/plugins-config: "{{ tpl (toYaml .Values.apisix.customPlugins) . | sha256sum }}"
```

**Proposal**

Update apisix pod template to allow tpl usage for annotations:

```yaml
metadata:
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    {{- with .Values.apisix.podAnnotations }}
      {{ tpl (toYaml .) $ | nindent 4}}
    {{- end }}
```
