### ISSUE TITLE
Helm validation and install fails when service.type is ClusterIP

### ISSUE THREAD

**Issue by AndreaVida** [apache/apisix-helm-chart#588]
When using service type `ClusterIP` Chart deployment fails with following error:

```
Service is invalid: spec.externalTrafficPolicy: Invalid value: "Cluster": may only be set when `type` is 'NodePort' or 'LoadBalancer'
```

A workaround is to set value like this:
```yaml
gateway:
    # -- Apache APISIX service type for user access itself
    type: ClusterIP
    # -- Setting how the Service route external traffic
    externalTrafficPolicy: ""
```

But this is still formally invalid and does not validate with schema [service-v1.json#/properties/spec/properties/externalTrafficPolicy/enum](https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.23.0-standalone-strict/service-v1.json#/properties/spec/properties/externalTrafficPolicy/enum)
