### ISSUE TITLE
"dashboard" need enabled in values.yaml?

### ISSUE THREAD

**Issue by sultra** [apache/apisix-helm-chart#623]
1.In the values.yaml file of apisix-helm-chart, does the "dashboard" section enable the "APISIX Dashboard" functionality without the need to install the "APISIX Dashboard Helm Chart"? If not, what does it mean?

2. In the values.yaml file of apisix-helm-chart, it mentions "dashboard.config.conf.etcd.username" and states, "Specifies etcd basic auth username if enable etcd auth." However, etcd only has the "etcd.auth.rbac.rootPassword" configuration, which seems to only allow configuring the root password. How can I set the etcd username and password for the dashboard?

**Comment by Baoyuantop** [comment]
To clarify the two questions:

1. The `dashboard` section in the **apisix** chart's `values.yaml` controls whether to deploy the apisix-dashboard as a **subchart** dependency. It does not embed dashboard functionality into the APISIX gateway itself.

2. For etcd authentication in the dashboard chart, the `apisix-dashboard` chart's own `values.yaml` supports etcd credentials (lines 88-107 in dashboard values.yaml):
```yaml
config:
  conf:
    etcd:
      endpoints:
        - apisix-etcd:2379
      username: ~    # etcd auth username
      password: ~    # etcd auth password
```

Closing as this is a documentation/usage question. If you still have questions, please feel free to reopen.
