### ISSUE TITLE
$listenPort breaks when containerPort != servicePort

### ISSUE THREAD

**Issue by acuteaura** [apache/apisix-helm-chart#666]
Some functionality in APISIX relies heavily on the listen port / `$listen_port` being the actual serving port.

* X-Forwarded-Port is set wrong, leading to some applications generating bad redirect URLs.
* `redirect` with `http_to_https` generates redirects with the wrong port.

Currently, the following values are required to get this functionality:

```
apisix:
  podSecurityContext:
    sysctls:
    - name: net.ipv4.ip_unprivileged_port_start
      value: "80"
  readinessProbe:
    failureThreshold: 6
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 1
    tcpSocket:
      port: 80
    timeoutSeconds: 1
gateway:
  http:
    containerPort: 80
  tls:
    containerPort: 443
```

This is a huge caveat to APISIX working as intended, it should either be visibly documented or the defaults should be changed.
