### ISSUE TITLE
Create a new proxy_cache zone using helm chart

### ISSUE THREAD

**Issue by chilcano** [apache/apisix-helm-chart#667]
Hi there!
Is there a way to create a new `proxy_cache` zone through existing helm chart?.

This is existing configuration used by helm chart:
* helm chart: https://github.com/apache/apisix-helm-chart/blob/master/charts/apisix/templates/configmap.yaml
* config.yaml: https://github.com/apache/apisix/blob/master/conf/config-default.yaml

If so not possible, what is the best way to provide a custom config for this `proxy_cache` plugin?
Regards.

**Comment by Baoyuantop** [comment]
You can configure a custom `proxy_cache` zone through `apisix.nginx.configurationSnippet` in `values.yaml` (lines 454-466). Use the `httpStart` section to add NGINX http-level directives:

```yaml
apisix:
  nginx:
    configurationSnippet:
      httpStart: |
        proxy_cache_path /tmp/disk_cache levels=1:2 keys_zone=my_cache:50m inactive=1d max_size=1g;
```

Alternatively, you can use `apisix.fullCustomConfig` (values.yaml lines 335-340) to provide a complete custom `config.yaml` with your desired NGINX configuration.

Closing as this is a usage question. If you still need help, please feel free to reopen.
