### ISSUE TITLE
Dependency etcd auto periodic compaction should be enabled by default.

### ISSUE THREAD

**Issue by pongpongcn** [apache/apisix-helm-chart#672]
charts/apisix/Chart.yaml

```yaml
etcd:
  extraEnvVars:
    - name: ETCD_AUTO_COMPACTION_RETENTION
      value: "1"
```

It's a trap, for most users.

Ref: https://github.com/apache/apisix-ingress-controller/issues/1830
