### ISSUE TITLE
aws-load-balancer-security-groups not working with NLB in EKS

### ISSUE THREAD

**Issue by creib** [apache/apisix-helm-chart#693]
Hi,

I am trying to deploy a Ingress Controller using a Network Loadbalancer (NLB) on AWS EKS using the Helm chart. In order to be able to configure security groups on the NLB, I added the annotation: aws-load-balancer-security-groups pointing to a predefined SecurityGroup. 

```
gateway:
  # -- Apache APISIX service type for user access itself
  type: LoadBalancer
  # -- Setting how the Service route external traffic
  # If you want to keep the client source IP, you can set this to Local.

  # ref: https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip
  externalTrafficPolicy: Cluster
  # type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-security-groups: sg-12345
  externalIPs: []
  # -- Apache APISIX service settings for http
  http:
```

This is not working as expected. The AWS Console tells me, that no Security Group has been applies. I am using Chart Version 1.9.0.

Anybody any idea why?

Thanks for your help.
