### ISSUE TITLE
apisix-ingress-controller Helm Chart features & fixes

### ISSUE THREAD

**Issue by mstefany** [apache/apisix-helm-chart#704]
We are currently working on implementation of `apisix` into our EKS cluster. And it seems that Helm Chart is missing some of the features or has some bugs. Instead of opening many issues for you to resolve, I have tried to submit PRs with fixes/improvements.

We are currently installing `apisix-ingress-controller` Helm Chart using Flux CD, so many things can be workaround using `kustomize` `postRenderer`, but having these directly in Helm Chart would make things easier, see:

```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-apisix
  namespace: ingress-apisix
spec:
  chart:
    spec:
      chart: [REDACTED]/apisix/apisix-ingress-controller
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: [REDACTED]
        namespace: flux-system
      version: 0.13.0
  interval: 1h
  postRenderers:
  - kustomize:
      patches:
      - patch: |
          - op: add
            path: /metadata/annotations/reloader.stakater.com~1auto
            value: "true"
          - op: add
            path: /spec/template/spec/containers/1/resources
            value: {"limits": {"cpu": "1", "memory": "1Gi"}, "requests": {"cpu": "100m", "memory": "128Mi"}}
          - op: add
            path: /spec/template/spec/containers/1/securityContext
            value: {"capabilities": {"add": ["NET_BIND_SERVICE"]}}
        target:
          kind: Deployment
          name: apisix-ingress-controller
          version: v1
  values:
  [...]
```

For this matter, I am submitting a overview of PRs for you to review and potentially merge (I don't mind further improving PRs if needed and if review is provided):

- Support for annotations in Deployment object (needed for reloader to work): https://github.com/apache/apisix-helm-chart/pull/697
- Support for PodDisruptionBudget policy: https://github.com/apache/apisix-helm-chart/pull/695
- Support for configuring resources of gateway container (kind of critical PR): https://github.com/apache/apisix-helm-chart/pull/694
- Support for configuring securityContext for gateway container: https://github.com/apache/apisix-helm-chart/pull/702
- Fix of TLS (SSL) configuration of gateway container: https://github.com/apache/apisix-helm-chart/pull/703

There is one more thing missing - support for enabling/disabling apisix plugins in the configMap (e.g. zipkin is enabled by default, but opentelemetry is not, and we would like to have it vice-versa).

EDIT:
Additional PRs:
- https://github.com/apache/apisix-helm-chart/pull/706
- https://github.com/apache/apisix-helm-chart/pull/712
