### ISSUE TITLE
Enabling discovery kubenetes services configuration doesn't list cluster existing endpoints in Dashboard Service list

### ISSUE THREAD

**Issue by singhajitk** [apache/apisix-helm-chart#734]
The cluster existing endpoints in not getting listed in Dashboard Service list after providing the discovery Kubernetes services configuration

My understanding is that existing cluster endpoints should get listed or available after search in Dashboard Service list

Steps to Reproduce:
1) Install APISIX with the apache / apisix-helm-chart with discovery Kubernetes services configuration
```
discovery:
  kubernetes:
    client:
      token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    default_weight: 50
    service:
      host: ${KUBERNETES_SERVICE_HOST}
      port: ${KUBERNETES_SERVICE_PORT}
      schema: https
```

Environment
APISIX version : - 3.8.0

Operating system : Linux apisix-647b4867df-79542 5.4.0-136-generic https://github.com/apache/apisix/pull/153~18.04.1-Ubuntu SMP Wed Nov 30 15:47:57 UTC 2022 x86_64 GNU/Linux

OpenResty / Nginx version:
    nginx version: openresty/1.21.4.2
    built by gcc 10.2.1 20210110 (Debian 10.2.1-6)
    built with OpenSSL 3.2.0 23 Nov 2023
   TLS SNI support enabled

APISIX Dashboard version, if relevant: 3.0.0
