### ISSUE TITLE
[help request ] 如何配置自定义的插件

### ISSUE THREAD

**Issue by lingbao08** [apache/apisix-helm-chart#790]
以前的apisix中，可以支持自定义配置插件。比如：
```yaml
apisix:
  extra_lua_path: '/usr/local/apisix/plugins/?.lua'
```
来指定自定义插件的地址。
同时在 `apisix.plugins` 属性中新增插件名即可。

但是在使用helm安装apisix（apisix + apisix-dashboard + apisix-ingress-controller）时，没有发现有可以配置自定义插件。
尝试过在apisix/values.yaml中的`apisix.plugins` 属性中设置，启动后会在apisix的pod中提示插件找不到文件。
这个文件的`apisix.customPlugins` 属性如果开启就要挂盘，还有什么新的配置文件，还有下面的属性看不懂（在单独使用apisix的时候，没有这么多属性）。

在apisix的官网和 https://apache.github.io/apisix-helm-chart/ 都没有找到该如何配置。

想问下，使用helm安装apisix系列（apisix + apisix-dashboard + apisix-ingress-controller）时，自定义插件如何设置？

**Comment by tian8280508** [comment]
同问 如何在helm管理的apisix下设置自定义插件

**Comment by Baoyuantop** [comment]
The current chart supports custom plugins via `apisix.customPlugins` in `values.yaml` (lines 580-600):

```yaml
apisix:
  customPlugins:
    enabled: true
    luaPath: "/opts/custom_plugins/?.lua"
    plugins:
      - name: "your-plugin-name"
        attrs: {}
        configMap:
          name: "your-configmap"
          mounts:
            - key: "plugin-file.lua"
              path: "/opts/custom_plugins"
```

Additionally, `apisix.luaModuleHook` (lines 290-306) provides another way to inject custom Lua modules with `luaPath` and `hookPoint` settings. Store your plugin code in a ConfigMap and reference it in the chart values.

Closing as this is a usage question. If you still need help, please feel free to reopen.
